# Generated by Django 4.1.3 on 2022-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chosen_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
